package com.dl.one;

import java.io.FileWriter;
import java.io.IOException;

public class Eg7 {

	public static void main(String[] args) throws IOException {
		FileWriter filewriter = new FileWriter("six.txt");
		
		filewriter.write("This the line generated by using the java");
		
		filewriter.close();
		
		System.out.println("File created and data inserted");
		

	}

}
